package com.securepay.entity;

public enum Permission {
    READ_TRANSACTIONS,
    CREATE_TRANSACTION,
    READ_PAYMENT_METHODS,
    CREATE_PAYMENT_METHOD,
    DELETE_PAYMENT_METHOD,
    READ_NOTIFICATIONS,
    MANAGE_PROFILE,
    READ_PAYMENT_LINKS,
    CREATE_PAYMENT_LINK,
    READ_ANALYTICS,
    READ_CUSTOMERS,
    MANAGE_USERS,
    MANAGE_MERCHANTS,
    READ_AUDIT_LOGS,
    MANAGE_SYSTEM_SETTINGS,
    VIEW_TRANSACTIONS,
    MAKE_PAYMENTS,
    MANAGE_PAYMENTS,
    VIEW_ANALYTICS,
    SYSTEM_ADMIN,
    FULL_ACCESS
}
